### ISSUE TITLE
Installation from instruction hangs at bcrypt==3.2.0

### ISSUE THREAD

**Issue by pm-mic** [andrequeiroz2/appi2c#1]
I'm sorry in advance, I'm really not that well known in the python framework. 

I tried to install appi2c both in a container and on a regular raspberry pi, and both times installation stalled with this particular error: 
```
Could not find a version that satisfies the requirement bcrypt==3.2.0 (from -r ./appi2c/requirements.txt (line 5)) (from versions: 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 2.0.0, 3.0.0, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.7)
No matching distribution found for bcrypt==3.2.0 (from -r ./appi2c/requirements.txt (line 5))
```
I tried forcing python 3 by deinstalling 2.7, but then I noticed the virtualenv (probably) defaults to 2.7. Not that sure how best to fix this. Hope you can update the installation instructions.

**Comment by andrequeiroz2** [comment]
Okay, I'll be evaluating a solution.
Thanks for the feedback.

**Comment by andrequeiroz2** [comment]
Some of the libs contained in the requirements list are independent and may have their repository changed, when installing your virtual environment make sure to install the latest version of python.

python3 -m pip install --upgrade pip
pip3 install virtualenv

If any lib continues to have an error, you can simply install individually.
ex: pip3 install bcrypt
